name: build

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle checksum
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Codegen tests
        run: ./gradlew -p catalog-codegen test
