name: build

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle checksum
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Build sample-app-resources Demo
        run: ./gradlew :sample-app-resources:buildDemoDebug :sample-app-resources:buildDemoRelease

      - name: Build sample-app-resources Full
        run: ./gradlew :sample-app-resources:buildFullDebug :sample-app-resources:buildFullRelease

      - name: Build sample-app-compose
        run: ./gradlew :sample-app-compose:buildDebug :sample-app-compose:buildRelease

  test:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Unit tests
        run: ./gradlew :catalog-gradle-plugin:test

  publish:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' && github.repository == 'flavioarfaria/Catalog'
    needs: test
    steps:
      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
        run: ./gradlew publishAllPublicationsToMavenCentral
